### ISSUE TITLE
Create header component

### ISSUE THREAD

**Issue by disnelrr** [disnelrr/mivetonline#4]
The header component contains the primary menu, the social links and a space between for custom text (like the phone number in the example).

![webdomiciliosheater](https://github.com/disnelrr/mivetonline/assets/35430665/641d6320-d635-46f3-b3bf-a4fa15b7b8dd)

**Note:** use the `tailwindcss` classes for the colors:

- blue: primary
- green: secondary

For instance, if you want to set the background color for a container with the selectec blue, you need to use the class `bg-primary`.

**You don't have to configure the colors in tailwind for this tasks, just use the existing ones (they will not match for the moment). In a separate task we will update the colors.**

**Comment by Sule98** [comment]
Falta el quinto icono dentro de el contenedor que contiene las redes sociales se desconoce nombre de la red social que esta en el diseño
